version: '3.4'

services:
  bss.dishdepot.api:
    image: ${DOCKER_REGISTRY-}bssdishdepotapi
    build:
      context: .
      dockerfile: src/BSS.DishDepot.Api/Dockerfile
    depends_on:
      - dishdepot.database
    ports:
      - "6035:6035"
  dishdepot.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dishdepot.database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1!
      - MSSQL_PID=Developer
    volumes:
      - ./.containers/homeprojects-db/data:/var/opt/mssql/data
      - ./.containers/homeprojects-db/log:/var/opt/mssql/log
      - ./.containers/homeprojects-db/secrets:/var/opt/mssql/secrets
    ports:
      - 1433:1433
volumes:
  cache:
    driver: local
