CREATE TABLE [DishDepot].[Users]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Email] NVARCHAR(100) NOT NULL,
	[PasswordHash] NVARCHAR(100) NOT NULL,
	[CreatedDateTime] DATETIME NOT NULL DEFAULT GETDATE(),	
	[ETag] ROWVERSION NOT NULL
);